- name: remove docker-ce
  hosts: "{{ variable_host }}"
  become: true

  tasks:

  - name: stop dcoker
    systemd: 
      name: docker 
      state: stopped
      enabled: no
  
  - name: remove docker
    yum: state=absent name={{ item }}
    with_items:
      - docker
      - docker-common
      - docker-selinux
      - docker-engine
      - docker-ce
      - docker-ee
      
  - name: Clean files
    file:
      state: absent
      path: "/var/lib/docker/"
      
  - name: Restart server
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
