- name: Join DTR
  hosts: "{{ variable_host }}"
  become: true

  tasks:
  - name: joindtr
    shell: docker run -i --rm docker/dtr join  --existing-replica-id {{replica_id}} --ucp-node {{ucp_node}} --ucp-insecure-tls --ucp-url https://{{ucp_url}} --ucp-username admin  --ucp-password {{ucp_pass}} --replica-http-port {{http_port}} --replica-https-port {{https_port}} 
