- name: Install zabbix client
  hosts: "{{ variable_host }}"
  become: true

  tasks:
  - name: Add repo
    yum:
      name: http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
      state: present

  - name: Install zabbix
    yum:
      name: zabbix-agent
      state: present


  - name: Edit Config File
    shell: |
      cat > /etc/zabbix/zabbix_agentd.conf << EOF
      PidFile=/var/run/zabbix/zabbix_agentd.pid
      LogFile=/var/log/zabbix/zabbix_agentd.log
      LogFileSize=0
      Server=zabbix.agonyweb.com
      ServerActive=zabbix.agonyweb.com
      Hostname=$(hostname)
      Include=/etc/zabbix/zabbix_agentd.d/*.conf



  - name: Enable/Start zabbix
    systemd:
      name: zabbix-agent
      state: started
      enabled: True

  - name: Add port to firewall
    command: firewall-cmd --add-port=10050/tcp --permanent

  - name: Reload Firewall
    command: firewall-cmd --reload
